# Generated by Django 4.0.5 on 2022-07-02 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threeknightsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exercize',
            new_name='Exercise',
        ),
    ]
